# Generated by Django 4.2.9 on 2024-01-14 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostEvent',
            new_name='EventPost',
        ),
    ]
